/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package movieticket;

import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author parep
 */
public class CustomerView extends javax.swing.JFrame {

    String mail;
    ArrayList<Cus> arr;
    /**
     * Creates new form CustomerView
     */
    public CustomerView(String mail) {
        this.mail=mail;
        initComponents();
    }

    public CustomerView() {
        initComponents();
        setIconImage(new ImageIcon("clap.png").getImage());
    }
    
    
    
    public final CustomerModel getData()
    {
        try {
            arr=new ArrayList<>();
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/movie", "root", "");
            Statement st=con.createStatement();
            //To change
            ResultSet rs=st.executeQuery("select movie_name,hall_no,date_format(date,'%d-%m-%y') as date,time,seats,no_of_seats,price,poster from details,payment where s_no= mov_no and mail="+mail+" order by date desc");            
            int s_no=0;
            while(rs.next())
            {
                s_no++;
                arr.add(new Cus(s_no, rs.getInt("no_of_seats"), rs.getInt("price"), rs.getInt("hall_no"), rs.getString("movie_name"), rs.getString("seats"), rs.getString("date"), rs.getString("time"), rs.getBytes("poster")));
            }
            String[] columns={"S. NO","Movie Name","Hall No","Date","Time","Seats","NO of Seats","Price","Poster"};
            Object[][] rows=new Object[arr.size()][10];
            for (int i = 0; i < arr.size(); i++) {
                rows[i][0]=arr.get(i).getS_no();
                rows[i][1]=arr.get(i).getMovName();
                rows[i][2]=arr.get(i).getHallno();
                rows[i][3]=arr.get(i).getDate();
                rows[i][4]=arr.get(i).getTime();
                rows[i][5]=arr.get(i).getSeats();
                rows[i][6]=arr.get(i).getNoofseats();
                rows[i][7]=arr.get(i).getPrice();
                if (arr.get(i).getPoster()!= null) {
                    ImageIcon image = new ImageIcon(new ImageIcon(arr.get(i).getPoster()).getImage()
                            .getScaledInstance(150, 120, Image.SCALE_SMOOTH));
                    rows[i][8] = image;
                } else {
                    rows[i][8] = null;
                }
            }
            CustomerModel mod=new CustomerModel(rows,columns);
            jTable1.setRowHeight(120);
            return mod;
        } catch (SQLException ex) {
            System.out.println(ex.toString());
            JOptionPane.showMessageDialog(null, "Check database connection");
        }
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        back = new javax.swing.JLabel();
        cancel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Customer View");

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setBackground(new java.awt.Color(153, 255, 153));
        jTable1.setForeground(new java.awt.Color(0, 0, 255));
        jTable1.setModel(getData());
        jTable1.setAlignmentX(1.0F);
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTable1.setDragEnabled(true);
        jTable1.setGridColor(new java.awt.Color(255, 55, 55));
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.getTableHeader().setReorderingAllowed(false);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTable1, org.jdesktop.beansbinding.ELProperty.create("true"), jTable1, org.jdesktop.beansbinding.BeanProperty.create("showHorizontalLines"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTable1, org.jdesktop.beansbinding.ELProperty.create("true"), jTable1, org.jdesktop.beansbinding.BeanProperty.create("showVerticalLines"));
        bindingGroup.addBinding(binding);

        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        //jTable1.getColumnModel().getColumn(8).setPreferredWidth(150);

        back.setFont(new java.awt.Font("Adobe Devanagari", 3, 18)); // NOI18N
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/movieticket/back.png"))); // NOI18N
        back.setText("  Back to Login Page");
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });

        cancel.setFont(new java.awt.Font("Adobe Devanagari", 3, 18)); // NOI18N
        cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/movieticket/cancel2.png"))); // NOI18N
        cancel.setText("Cancel Tickets");
        cancel.setVisible(false);
        cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1036, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cancel)
                .addGap(44, 44, 44)
                .addComponent(back)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancel))
                .addContainerGap())
        );

        bindingGroup.bind();

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        new CustomerLogin().setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_backMouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        if(jTable1.getSelectedRowCount()==1)
        {
            try {
                int row=jTable1.getSelectedRow();
                String date=arr.get(row).getDate();
                Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/movie","root","");
                Statement st=con.createStatement();
                ResultSet rs=st.executeQuery("select datediff(date(now()),date_format(\'"+date+"\',\'%d-%m-%y\')) from dual");
                rs.next();
                int diff=rs.getInt(1);
                System.out.println(diff);
                if(diff<0)
                {
                    cancel.setVisible(true);
                }
                else if(diff==0)
                {
                    String time=arr.get(row).getTime();
                    rs=st.executeQuery("select timediff(time(now()),\'"+time+":00\') from dual");
                    rs.next();
                    String[] timediff=rs.getString(1).split(":");
                    if(Integer.parseInt(timediff[0])>=6)
                    {
                        cancel.setVisible(true);
                    }
                    
                }
                else
                {
                    cancel.setVisible(false);
                }
            } catch (SQLException ex) {
                cancel.setVisible(false);
                Logger.getLogger(CustomerView.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void cancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseClicked
        try {
            int row=jTable1.getSelectedRow();
            String seats=arr.get(row).getSeats();
            String mov=arr.get(row).getMovName();
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/movie","root","");
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("select s_no from details where movie_name=\'"+mov+"\' and date=date_format(\'"+arr.get(row).getDate()+"\',\'%d-%m-%y\') and time=\'"+arr.get(row).getTime()+"\'" );
            rs.next();
            int sno=rs.getInt(1);
            System.out.println("sno: "+sno);
            System.out.println("seats"+seats);
            rs=st.executeQuery("select seats from seats where s_no="+sno);
            rs.next();
            String tseats=rs.getString(1);
            tseats=tseats.replace(seats,"0,");
            System.out.println("tseats: "+tseats);
            String sql="delete from payment where mov_no="+sno+" and mail="+mail+" and seats=\'"+seats+"\'";
            int raffected=st.executeUpdate(sql);
            System.out.println("No of rows affected: "+raffected);
            if(raffected!=0)
            {
                System.out.println("Seats Table rows affected: "+st.executeUpdate("update seats set seats=\'"+tseats+"\' where s_no="+sno));
                JOptionPane.showMessageDialog(null, "Deleted Successfully");
                new CustomerLogin().setVisible(true);
                dispose();
                jTable1.setModel(getData());
            }
            else
            {
                System.out.println("Query: "+sql);
            }
        } catch (SQLException ex) {
            Logger.getLogger(CustomerView.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Exception Occured!..");
        }
    }//GEN-LAST:event_cancelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerView("\"vamshireddy.m@vitap.ac.in\"").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JLabel cancel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
